### PR TITLE
Add Hotspot Safepoint metrics

### PR DESCRIPTION
**Pull request by DanielThomas**
Add hotspot safepoint metrics to help identify when safepoints and safepoint sync times are a problem. Unfortunately this relies on a propriety API, but there's no other way of getting at this at runtime on JDK 8 through latest. JFR event streams are JDK 15 and later for instance, and this is so much simpler. Some background here:

https://mail.openjdk.org/pipermail/serviceability-dev/2021-June/038222.html

This came up in the context of issue with I/O bound GC pauses on JDK 17:

https://twitter.com/DannyThomas/status/1546758318492102657

While I was at it, I went looking for any other causes of safepoint I/O latency and issues with safepoint sync times, and I can think of several places where we could be affected not only by that, but time-to-safepoint effective pauses where we're in JNI, etc:

- https://www.evanjones.ca/jvm-mmap-pause.html
- https://blanco.io/blog/jvm-safepoint-pauses/#analyzing-safepoint-pauses

### CODE REVIEW

**Comment by DanielThomas** [comment]
Looks like `--release` isn't aware of different package access between JDK versions, and you can't specify `{{--add-exports}}.

https://bugs.openjdk.org/browse/JDK-8178152

**Comment by DanielThomas** [comment]
@brharrington realized this is much simpler if I we just use toolchains. Build changes moved to a separate commit before the hotspot metrics - see what you think.

**Comment by brharrington** [comment]
Thanks, I have started looking at it and should be able to go through it in detail later today.

**Comment by brharrington** [comment]
I refactored it a bit to model as timers: https://github.com/brharrington/spectator/commit/6eff138815e00eec5725c7adac7c0da2d4c53e1e, doesn't look like I can push to the PR branch. Anyway let me know what you think. I'm going to build a version of the jar and run it on some test instances over the weekend.

**Comment by DanielThomas** [comment]
That's awesome, thanks @brharrington! Really have to work on my Spectator foo, I never seem to get this right the first time :)

**Comment by brharrington** [comment]
Closing in favor of #980

**Pull request closed without merging**
