### PR TITLE
Serializable Registry

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by brharrington** [comment]
Why do you want the registry to be serializable?

**Comment by joan38** [comment]
Actually I found a PR I've done in the past https://github.com/Netflix/spectator/pull/737
We are using this in Flink and things need to be serializable. We have a workaround but I was wondering if we can remove it.

In that PR I said that it's not going to work. I haven't dived into this further but I'm wondering if this requires a larger change to make it serializable.

**Comment by brharrington** [comment]
Registry is just a base interface, all implementations would have to be made serializable. In general I don't think it is a good idea as things like gauge polling allow registering callbacks for interrogating the state of arbitrary objects. Also the registry will typically have context for the local instance and should normally be a singleton in the process. Running multiple instances or transferring to another instance would not work correctly.

**Comment by joan38** [comment]
That make sense. I'm closing this one for now.

**Pull request closed without merging**
